# Generated by Django 5.1 on 2024-10-02 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deceptoApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('login_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deceptoApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('reply', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(default='open', max_length=100)),
                ('login_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deceptoApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100)),
                ('current_date', models.DateTimeField(auto_now_add=True)),
                ('review', models.CharField(max_length=100)),
                ('login_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deceptoApp.user')),
            ],
        ),
    ]
