# Generated by Django 5.1 on 2024-10-05 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deceptoApp', '0002_admin_category_complaint_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
