# Generated by Django 5.1 on 2024-10-05 07:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deceptoApp', '0003_alter_complaint_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='review',
            name='current_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
